name: flutter_nfc_reader
description: A nfc reader plugin for iOS and Android.
version: 0.0.2
author: Matteo Crippa <>
homepage: https://github.com/matteocrippa

environment:
  sdk: '>=1.19.0 <3.0.0'
  flutter: ^0.5.5

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.flutternfcreader
    pluginClass: FlutterNfcReaderPlugin