name: flutter_nfc_reader
description: A nfc reader plugin for iOS and Android.
version: 0.0.1
author: Matteo Crippa
homepage: https://github.com/matteocrippa

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.flutternfcreader
    pluginClass: FlutterNfcReaderPlugin

  environment:
    sdk: ">=1.19.0 <2.0.0"